/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface FileData {
  file: string
  hash: string
}
export function hashArray(input: Array<string>): string
export function hashFile(file: string): FileData | null
export function hashFiles(workspaceRoot: string): Record<string, string>
export interface WatchEvent {
  path: string
  type: EventType
}
export const enum EventType {
  create = 'create',
  delete = 'delete',
  update = 'update'
}
export class Watcher {
  origin: string
  constructor(origin: string, callback: (err: string | null, paths: WatchEvent[]) => void)
  start(): void
}
