/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface FileData {
  file: string
  hash: string
}
export function hashArray(input: Array<string>): string
export function hashFile(file: string): FileData | null
export function hashFiles(workspaceRoot: string): Record<string, string>
/**
 * Newly created files will have the `update` EventType as well.
 * This simplifies logic between OS's, IDEs and git operations
 */
export const enum EventType {
  delete = 'delete',
  update = 'update'
}
export interface WatchEvent {
  path: string
  type: EventType
}
export class Watcher {
  origin: string
  constructor(origin: string)
  watch(callback: (err: string | null, paths: WatchEvent[]) => void): void
  stop(): Promise<void>
}
