#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Action {
    Tick,
    Render,
    Resize(u16, u16),
    Quit,
    CancelQuit,
    Error(String),
    Help,
    EnterFilterMode,
    ClearFilter,
    AddFilterChar(char),
    RemoveFilterChar,
    ScrollUp,
    ScrollDown,
    // Represents the visual selection of a task in the task list (it may or not have its output pane visible while selected)
    SelectTask(String),
    PinTask(String, usize),
    UnpinTask(String, usize),
    UnpinAllTasks,
    NextPage,
    PreviousPage,
    ToggleOutput,
    FocusNext,
    FocusPrevious,
    ScrollPaneUp(usize),
    ScrollPaneDown(usize),
}
