use super::components::tasks_list::TaskStatus;

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Action {
    Tick,
    Render,
    Resize(u16, u16),
    Quit,
    CancelQuit,
    Error(String),
    Help,
    EnterFilterMode,
    ClearFilter,
    AddFilterChar(char),
    RemoveFilterChar,
    ScrollUp,
    ScrollDown,
    PinTask(String, usize),
    UnpinTask(String, usize),
    UnpinAllTasks,
    SortTasks,
    NextPage,
    PreviousPage,
    NextTask,
    PreviousTask,
    ToggleOutput,
    FocusNext,
    FocusPrevious,
    SetSpacebarMode(bool),
    ScrollPaneUp(usize),
    ScrollPaneDown(usize),
    UpdateTaskStatus(String, TaskStatus),
    UpdateCloudMessage(String),
}
