export type UiFramework =
  | '@storybook/angular'
  | '@storybook/html-webpack5'
  | '@storybook/nextjs'
  | '@storybook/preact-webpack5'
  | '@storybook/react-webpack5'
  | '@storybook/react-vite'
  | '@storybook/server-webpack5'
  | '@storybook/svelte-webpack5'
  | '@storybook/svelte-vite'
  | '@storybook/sveltekit'
  | '@storybook/vue-webpack5'
  | '@storybook/vue-vite'
  | '@storybook/vue3-webpack5'
  | '@storybook/vue3-vite'
  | '@storybook/web-components-webpack5'
  | '@storybook/web-components-vite';
