module.exports = {
  projects: [
    '<rootDir>/packages/tao',
    '<rootDir>/packages/workspace',
    '<rootDir>/packages/web',
    '<rootDir>/packages/cypress',
    '<rootDir>/packages/jest',
    '<rootDir>/packages/storybook',
    '<rootDir>/packages/react',
    '<rootDir>/packages/nx-plugin',
    '<rootDir>/packages/node',
    '<rootDir>/packages/next',
    '<rootDir>/packages/nest',
    '<rootDir>/packages/linter',
    '<rootDir>/packages/express',
    '<rootDir>/packages/eslint-plugin-nx',
    '<rootDir>/packages/create-nx-workspace',
    '<rootDir>/packages/create-nx-plugin',
    '<rootDir>/packages/cli',
    '<rootDir>/packages/angular',
    '<rootDir>/packages/gatsby',
    '<rootDir>/dep-graph/dep-graph',
    '<rootDir>/nx-dev/nx-dev',
    '<rootDir>/nx-dev/ui-common',
    '<rootDir>/nx-dev/feature-doc-viewer',
    '<rootDir>/nx-dev/data-access-documents',
  ],
};
