packages:
  - 'packages/*'
  - 'e2e/*'
  - 'graph/*'
  - 'nx-dev/*'
  - 'tools/*'
  - 'astro-docs'
  - 'examples/*/*'
  - 'examples/angular-rspack/module-federation/host'
  - 'examples/angular-rspack/module-federation/remote'
  - 'packages/nx/native-packages/*'
