packages:
  - 'packages/*'
  - 'e2e/*'
  - 'graph/*'
  - 'nx-dev/*'
  - 'tools/documentation/*'
  - 'tools/*'
  - 'typedoc-theme'
  - 'astro-docs'
  - 'examples/*/*'
  - 'packages/nx/native-packages/*'
