/**
 * Builds the static nx.dev router site into dist/:
 * - copies public/ static assets
 * - writes _redirects = the checked-in rules + generated astro-docs proxy
 *   rules (the astro URL is environment-dependent, so those rules cannot be
 *   checked in)
 * - writes the sitemap.xml index pointing at the Framer, blog, and astro-docs
 *   sitemaps
 */
import { cpSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'fs';
import { join, resolve } from 'path';

const projectRoot = resolve(import.meta.dirname, '..');
const distDir = join(projectRoot, 'dist');

function resolveAstroUrl() {
  // For deploy previews, always point to the matching astro-docs preview
  // (overrides any site-level env var that would otherwise point to production).
  if (
    process.env.NETLIFY &&
    process.env.CONTEXT === 'deploy-preview' &&
    process.env.REVIEW_ID
  ) {
    const url = `https://deploy-preview-${process.env.REVIEW_ID}--nx-docs.netlify.app`;
    console.log(`[deploy-preview] astro-docs URL overridden to: ${url}`);
    return url;
  }
  if (process.env.NEXT_PUBLIC_ASTRO_URL) {
    return process.env.NEXT_PUBLIC_ASTRO_URL.replace(/\/$/, '');
  }
  if (process.env.NETLIFY && process.env.CONTEXT === 'production') {
    throw new Error(
      'The NEXT_PUBLIC_ASTRO_URL environment variable is not set. Please set it to the URL of the Astro site.'
    );
  }
  // For local builds, default to the canary docs.
  return 'https://master--nx-docs.netlify.app';
}

const astroUrl = resolveAstroUrl();
const siteUrl = process.env.NX_DEV_URL || 'https://nx.dev';
const noIndex = process.env.NEXT_PUBLIC_NO_INDEX === 'true';

rmSync(distDir, { recursive: true, force: true });
mkdirSync(distDir, { recursive: true });

cpSync(join(projectRoot, 'public'), distDir, { recursive: true });

const staticRedirects = readFileSync(join(projectRoot, '_redirects'), 'utf-8');
// Note: /.netlify/* is a reserved path and cannot be a redirect source
// (Netlify rejects the rule). The platform Image CDN serves
// /.netlify/images directly, resolving url= paths through this site's
// routing - including the /docs/* proxy below - so astro-docs image
// URLs keep working without a rule.
const generatedRedirects = `
# --- generated by scripts/build-site.mjs (astro-docs proxy) ---
/robots.txt ${astroUrl}/docs/robots.txt 200
/llms.txt ${astroUrl}/docs/llms.txt 200
/llms-full.txt ${astroUrl}/docs/llms-full.txt 200
/docs/* ${astroUrl}/docs/:splat 200
`;
writeFileSync(
  join(distDir, '_redirects'),
  staticRedirects + generatedRedirects
);

const sitemaps = noIndex
  ? []
  : [
      `${siteUrl}/sitemap-1.xml`,
      `${siteUrl}/sitemap-2.xml`,
      `${siteUrl}/docs/sitemap-index.xml`,
    ];
const sitemapIndex = `<?xml version="1.0" encoding="UTF-8"?>
<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${sitemaps.map((url) => `<sitemap><loc>${url}</loc></sitemap>`).join('\n')}
</sitemapindex>
`;
writeFileSync(join(distDir, 'sitemap.xml'), sitemapIndex);

console.log(`Built nx.dev router site to ${distDir} (astro: ${astroUrl})`);
