import { logger } from '@nx/devkit';

// TODO(v24): Remove the @nx/rspack:rspack and @nx/rspack:dev-server
// executors. The inferred plugin (@nx/rspack/plugin) and the
// convert-to-inferred generator stay supported.
export const RSPACK_EXECUTOR_DEPRECATION_MESSAGE =
  'The `@nx/rspack:rspack` executor is deprecated and will be removed in Nx v24. Run `nx g @nx/rspack:convert-to-inferred` to migrate to the `@nx/rspack/plugin` inferred targets. See https://nx.dev/docs/guides/tasks--caching/convert-to-inferred for details.';

export const RSPACK_DEV_SERVER_EXECUTOR_DEPRECATION_MESSAGE =
  'The `@nx/rspack:dev-server` executor is deprecated and will be removed in Nx v24. Run `nx g @nx/rspack:convert-to-inferred` to migrate to the `@nx/rspack/plugin` inferred targets. See https://nx.dev/docs/guides/tasks--caching/convert-to-inferred for details.';

export function warnRspackExecutorDeprecation(): void {
  logger.warn(RSPACK_EXECUTOR_DEPRECATION_MESSAGE);
}

export function warnRspackDevServerExecutorDeprecation(): void {
  logger.warn(RSPACK_DEV_SERVER_EXECUTOR_DEPRECATION_MESSAGE);
}

export function warnRspackExecutorGenerating(): void {
  logger.warn(
    'Generating targets that use the deprecated `@nx/rspack:rspack` and `@nx/rspack:dev-server` executors. These executors will be removed in Nx v24. Run `nx g @nx/rspack:convert-to-inferred` next to migrate these targets to the `@nx/rspack/plugin` inferred plugin and prevent future generators from emitting executor targets. See https://nx.dev/docs/guides/tasks--caching/convert-to-inferred for details.'
  );
}

// Helper behavior was removed in v24; exports remain only as inert stubs.
// Keep their exports loadable so old configs do not block graph creation.
export const RSPACK_COMPOSE_HELPERS_DEPRECATION_MESSAGE =
  'The compose config helpers from `@nx/rspack` were removed in Nx v24. The remaining exports are inert compatibility stubs and do not configure builds. Migrate to a standard rspack config using `NxAppRspackPlugin` from `@nx/rspack/app-plugin`. Follow the config-helper migration instructions generated by `nx migrate`. Executor conversion is a separate migration.';

let composeHelpersWarned = false;
let suppressDepth = 0;

// Nx-internal entry points compose these helpers themselves (e.g. the rspack
// executor). They wrap their synchronous composition in this so the warning
// fires only for user-authored configs.
export function suppressRspackComposeHelperWarnings<T>(fn: () => T): T {
  suppressDepth++;
  try {
    return fn();
  } finally {
    suppressDepth--;
  }
}

// Warn once per process so a `composePlugins(withNx(), withReact())` chain logs
// a single line, not one per helper, and HMR reloads don't repeat it.
export function warnRspackComposeHelpersDeprecation(): void {
  if (suppressDepth > 0 || composeHelpersWarned) return;
  composeHelpersWarned = true;
  logger.warn(RSPACK_COMPOSE_HELPERS_DEPRECATION_MESSAGE);
}
