import { logger } from '@nx/devkit';

// Helper behavior was removed in v24; exports remain only as inert stubs.
// Keep the export loadable while existing webpack configs are migrated.
export const REACT_WITH_REACT_DEPRECATION_MESSAGE =
  'The `withReact` config helper from `@nx/react` was removed in Nx v24. The remaining export is an inert compatibility stub and does not configure builds. Use `NxReactWebpackPlugin` from `@nx/react/webpack-plugin` in a standard webpack config. Follow the webpack config-helper migration instructions generated by `nx migrate`. Executor conversion is a separate migration.';

let withReactWarned = false;
let suppressDepth = 0;

// Nx-internal entry points compose `withReact` themselves (e.g. the storybook
// and component-testing presets). They wrap their synchronous composition in
// this so the warning fires only for user-authored configs.
export function suppressReactComposeHelperWarnings<T>(fn: () => T): T {
  suppressDepth++;
  try {
    return fn();
  } finally {
    suppressDepth--;
  }
}

// Warn once per process so HMR reloads and repeated config evaluation don't
// repeat the message.
export function warnReactWithReactDeprecation(): void {
  if (suppressDepth > 0 || withReactWarned) return;
  withReactWarned = true;
  logger.warn(REACT_WITH_REACT_DEPRECATION_MESSAGE);
}
