export const iconsMap: Record<string, string> = {
  angular: '/images/icons/angular.svg',
  cli: '/images/icons/nx.svg',
  cypress: '/images/icons/cypress.svg',
  detox: '/images/icons/react.svg',
  devkit: '/images/icons/nx.svg',
  'eslint-plugin-nx': '/images/icons/eslint.svg',
  expo: '/images/icons/expo.svg',
  express: '/images/icons/express.svg',
  jest: '/images/icons/jest.svg',
  js: '/images/icons/javascript.svg',
  linter: '/images/icons/eslint.svg',
  nest: '/images/icons/nestjs.svg',
  next: '/images/icons/nextdotjs.svg',
  node: '/images/icons/nodedotjs.svg',
  nx: '/images/icons/nx.svg',
  'nx-plugin': '/images/icons/nx.svg',
  react: '/images/icons/react.svg',
  'react-native': '/images/icons/react.svg',
  rollup: '/images/icons/rollup.svg',
  storybook: '/images/icons/storybook.svg',
  web: '/images/icons/html5.svg',
  webpack: '/images/icons/webpack.svg',
  workspace: '/images/icons/nx.svg',
};
