// This file is autogenerated in the node_modules when using Pnpm

export default `hoistPattern:
  - '*'
hoistedDependencies:
  ansi-regex@5.0.1:
    ansi-regex: private
  eastasianwidth@0.2.0:
    eastasianwidth: private
  emoji-regex@8.0.0:
    emoji-regex: private
  is-fullwidth-code-point@3.0.0:
    is-fullwidth-code-point: private
  strip-ansi@6.0.1:
    strip-ansi: private
included:
  dependencies: true
  devDependencies: true
  optionalDependencies: true
injectedDeps: {}
layoutVersion: 5
nodeLinker: isolated
packageManager: pnpm@9.15.0
pendingBuilds: []
prunedAt: Mon, 05 Jan 2026 14:44:36 GMT
publicHoistPattern:
  - '*eslint*'
  - '*prettier*'
registries:
  default: https://registry.npmjs.org/
skipped: []
storeDir: /Users/james/Library/pnpm/store/v3
virtualStoreDir: .pnpm
virtualStoreDirMaxLength: 120
`;
