/**
 * Constants for telemetry sanitization.
 */

/**
 * Standard target names that are safe to include in telemetry as-is.
 * Custom targets will be reported as '[custom]'.
 */
export const STANDARD_TARGETS = new Set([
  'build',
  'serve',
  'test',
  'lint',
  'e2e',
  'dev',
  'start',
  'preview',
  'deploy',
  'publish',
  'typecheck',
  'format',
  'check',
  'clean',
  'package',
  'release',
  'storybook',
  'build-storybook',
  'compodoc',
  'extract-i18n',
  'prerender',
  'server',
  'ssr-server',
  'static-server',
]);

/**
 * Standard configuration names that are safe to include in telemetry as-is.
 * Custom configurations will be reported as '[custom]'.
 */
export const STANDARD_CONFIGS = new Set([
  'production',
  'development',
  'staging',
  'test',
  'ci',
  'debug',
  'release',
]);

/**
 * Known Nx plugin prefixes. Plugins with these prefixes are safe to report.
 */
export const KNOWN_PLUGIN_PREFIXES = ['@nx/', '@nrwl/'];

/**
 * Known first-party Nx generators that have specific argument allowlists.
 */
export const KNOWN_NX_GENERATORS = new Set([
  '@nx/react:component',
  '@nx/react:library',
  '@nx/react:application',
  '@nx/react:hook',
  '@nx/react:redux',
  '@nx/react:storybook-configuration',
  '@nx/angular:component',
  '@nx/angular:library',
  '@nx/angular:application',
  '@nx/angular:directive',
  '@nx/angular:pipe',
  '@nx/angular:service',
  '@nx/angular:module',
  '@nx/angular:storybook-configuration',
  '@nx/node:application',
  '@nx/node:library',
  '@nx/nest:application',
  '@nx/nest:library',
  '@nx/nest:controller',
  '@nx/nest:service',
  '@nx/nest:module',
  '@nx/next:application',
  '@nx/next:library',
  '@nx/next:page',
  '@nx/next:component',
  '@nx/vue:application',
  '@nx/vue:library',
  '@nx/vue:component',
  '@nx/nuxt:application',
  '@nx/js:library',
  '@nx/js:init',
  '@nx/web:application',
  '@nx/express:application',
  '@nx/remix:application',
  '@nx/remix:library',
  '@nx/expo:application',
  '@nx/react-native:application',
  '@nx/workspace:library',
  '@nx/workspace:move',
  '@nx/workspace:remove',
  '@nx/plugin:plugin',
  '@nx/plugin:generator',
  '@nx/plugin:executor',
  '@nx/plugin:migration',
  '@nx/storybook:configuration',
  '@nx/cypress:configuration',
  '@nx/jest:configuration',
  '@nx/vite:configuration',
  '@nx/webpack:configuration',
  '@nx/eslint:configuration',
  '@nx/rspack:configuration',
]);

/**
 * Flags that should never have their values recorded.
 * The presence of these flags may be recorded, but values are always redacted.
 */
export const SENSITIVE_FLAGS = new Set([
  // Authentication
  'token',
  'access-token',
  'accessToken',
  'api-key',
  'apiKey',
  'secret',
  'password',
  'pass',
  'pwd',
  'credential',
  'credentials',
  'auth',
  'authorization',

  // Paths that might contain usernames
  'path',
  'file',
  'dir',
  'directory',
  'output',
  'outputPath',
  'output-path',
  'input',
  'inputPath',
  'input-path',
  'root',
  'cwd',
  'config',
  'configPath',
  'config-path',
  'tsConfig',
  'ts-config',

  // URLs and endpoints
  'url',
  'uri',
  'endpoint',
  'host',
  'hostname',
  'baseUrl',
  'base-url',
  'baseHref',
  'base-href',

  // Names that could be identifying
  'name',
  'project',
  'projectName',
  'project-name',
  'app',
  'appName',
  'app-name',
  'lib',
  'libName',
  'lib-name',

  // Environment
  'env',
  'environment',
]);

/**
 * Flags that are safe to record with their full values.
 * These are typically boolean flags or flags with a known set of values.
 */
export const SAFE_FLAGS = new Set([
  // Boolean flags
  'verbose',
  'v',
  'quiet',
  'q',
  'help',
  'h',
  'version',
  'dry-run',
  'dryRun',
  'skip-nx-cache',
  'skipNxCache',
  'skip-cache',
  'skipCache',
  'watch',
  'w',
  'parallel',
  'interactive',
  'no-interactive',
  'noInteractive',
  'force',
  'f',
  'all',
  'a',
  'affected',
  'prod',
  'production',
  'dev',
  'development',
  'debug',
  'ci',
  'clearCache',
  'clear-cache',
  'resetCache',
  'reset-cache',
  'daemon',
  'no-daemon',
  'noDaemon',
  'cloud',
  'no-cloud',
  'noCloud',
  'graph',
  'no-graph',
  'noGraph',
  'open',
  'no-open',
  'noOpen',
  'ssr',
  'no-ssr',
  'noSsr',
  'hmr',
  'no-hmr',
  'noHmr',
  'inspect',
  'no-inspect',
  'noInspect',
  'coverage',
  'no-coverage',
  'noCoverage',
  'codeCoverage',
  'code-coverage',
  'bail',
  'no-bail',
  'noBail',
  'cache',
  'no-cache',
  'noCache',
  'silent',
  's',
  'json',
  'plain',
  'uncommitted',
  'untracked',
  'base',
  'head',
  'files',
  'exclude',
  'only-failed',
  'onlyFailed',
  'skip-remote-cache',
  'skipRemoteCache',
  'no-agents',
  'noAgents',

  // Numeric/limited values
  'maxParallel',
  'max-parallel',
  'parallel',
  'retries',
  'retry',
  'port',
  'poll',
  'batch',
  'batch-size',
  'batchSize',

  // Standard option values
  'runner',
  'target',
  'targets',
  'configuration',
  'c',
  'projects',
  'exclude',
  'type',
  'bundler',
  'style',
  'linter',
  'framework',
  'preset',
  'unitTestRunner',
  'unit-test-runner',
  'e2eTestRunner',
  'e2e-test-runner',
  'routing',
  'standalone',
  'inlineStyle',
  'inline-style',
  'inlineTemplate',
  'inline-template',
  'skipTests',
  'skip-tests',
  'skipFormat',
  'skip-format',
  'skipPackageJson',
  'skip-package-json',
  'skipInstall',
  'skip-install',
  'skipTsConfig',
  'skip-ts-config',
  'strict',
  'no-strict',
  'noStrict',
  'publishable',
  'buildable',
  'importPath',
  'import-path',
  'tags',
  'directory',
  'flat',
  'no-flat',
  'noFlat',
  'export',
  'no-export',
  'noExport',
  'prefix',
  'selector',
  'changeDetection',
  'change-detection',
  'viewEncapsulation',
  'view-encapsulation',
  'module',
  'compiler',
  'skipSelector',
  'skip-selector',
]);

/**
 * Commands that are safe to record.
 */
export const KNOWN_COMMANDS = new Set([
  'run',
  'run-many',
  'affected',
  'build',
  'serve',
  'test',
  'lint',
  'e2e',
  'generate',
  'g',
  'new',
  'init',
  'migrate',
  'graph',
  'dep-graph',
  'affected:graph',
  'affected:dep-graph',
  'print-affected',
  'format',
  'format:check',
  'format:write',
  'workspace-lint',
  'workspace-generator',
  'list',
  'report',
  'reset',
  'daemon',
  'watch',
  'show',
  'release',
  'repair',
  'exec',
  'add',
  'sync',
  'sync:check',
  'login',
  'logout',
  'connect',
  'connect-to-nx-cloud',
  'view-logs',
]);
