export const targetOptionsToCliMap = {
  fix: 'fix',
  format: 'format',
  cache: 'cache',
  cacheLocation: 'cache-location',
  cacheStrategy: 'cache-strategy',
  noEslintrc: 'no-eslintrc',
  outputFile: 'output-file',
  maxWarnings: 'max-warnings',
  quiet: 'quiet',
  ignorePath: 'ignore-path',
  rulesdir: 'rulesdir',
  resolvePluginsRelativeTo: 'resolve-plugins-relative-to',
  reportUnusedDisableDirectives: 'report-unused-disable-directives',
  printConfig: 'print-config',
};
