// This file is autogenerated in the node_modules when using Pnpm

export default `hoistPattern:
  - '*'
hoistedDependencies:
  /@eslint/eslintrc/1.3.3:
    '@eslint/eslintrc': public
  /@humanwhocodes/config-array/0.11.7:
    '@humanwhocodes/config-array': private
  /@humanwhocodes/module-importer/1.0.1:
    '@humanwhocodes/module-importer': private
  /@humanwhocodes/object-schema/1.2.1:
    '@humanwhocodes/object-schema': private
  /@nodelib/fs.scandir/2.1.5:
    '@nodelib/fs.scandir': private
  /@nodelib/fs.stat/2.0.5:
    '@nodelib/fs.stat': private
  /@nodelib/fs.walk/1.2.8:
    '@nodelib/fs.walk': private
  /@nrwl/cli/15.3.0:
    '@nrwl/cli': private
  /@nrwl/tao/15.3.0:
    '@nrwl/tao': private
  /@parcel/watcher/2.0.4:
    '@parcel/watcher': private
  /@phenomnomnominal/tsquery/4.1.1_typescript@4.8.4:
    '@phenomnomnominal/tsquery': private
  /@types/json5/0.0.29:
    '@types/json5': private
  /@yarnpkg/lockfile/1.1.0:
    '@yarnpkg/lockfile': private
  /@yarnpkg/parsers/3.0.0-rc.32:
    '@yarnpkg/parsers': private
  /@zkochan/js-yaml/0.0.6:
    '@zkochan/js-yaml': private
  /acorn-jsx/5.3.2_acorn@8.8.1:
    acorn-jsx: private
  /acorn/8.8.1:
    acorn: private
  /ajv/6.12.6:
    ajv: private
  /ansi-colors/4.1.3:
    ansi-colors: private
  /ansi-regex/5.0.1:
    ansi-regex: private
  /ansi-styles/4.3.0:
    ansi-styles: private
  /anymatch/3.1.3:
    anymatch: private
  /app-root-path/3.1.0:
    app-root-path: private
  /argparse/2.0.1:
    argparse: private
  /async/3.2.4:
    async: private
  /asynckit/0.4.0:
    asynckit: private
  /axios/1.2.1:
    axios: private
  /balanced-match/1.0.2:
    balanced-match: private
  /base64-js/1.5.1:
    base64-js: private
  /binary-extensions/2.2.0:
    binary-extensions: private
  /bl/4.1.0:
    bl: private
  /brace-expansion/1.1.11:
    brace-expansion: private
  /braces/3.0.2:
    braces: private
  /buffer/5.7.1:
    buffer: private
  /callsites/3.1.0:
    callsites: private
  /chalk/4.1.2:
    chalk: private
  /chokidar/3.5.3:
    chokidar: private
  /cli-cursor/3.1.0:
    cli-cursor: private
  /cli-spinners/2.6.1:
    cli-spinners: private
  /cliui/8.0.1:
    cliui: private
  /color-convert/2.0.1:
    color-convert: private
  /color-name/1.1.4:
    color-name: private
  /combined-stream/1.0.8:
    combined-stream: private
  /concat-map/0.0.1:
    concat-map: private
  /cross-spawn/7.0.3:
    cross-spawn: private
  /debug/4.3.4:
    debug: private
  /deep-is/0.1.4:
    deep-is: private
  /define-lazy-prop/2.0.0:
    define-lazy-prop: private
  /delayed-stream/1.0.0:
    delayed-stream: private
  /doctrine/3.0.0:
    doctrine: private
  /dotenv/10.0.0:
    dotenv: private
  /duplexer/0.1.2:
    duplexer: private
  /ejs/3.1.8:
    ejs: private
  /emoji-regex/8.0.0:
    emoji-regex: private
  /end-of-stream/1.4.4:
    end-of-stream: private
  /enquirer/2.3.6:
    enquirer: private
  /escalade/3.1.1:
    escalade: private
  /escape-string-regexp/4.0.0:
    escape-string-regexp: private
  /eslint-rule-composer/0.3.0:
    eslint-rule-composer: public
  /eslint-scope/7.1.1:
    eslint-scope: public
  /eslint-utils/3.0.0_eslint@8.29.0:
    eslint-utils: public
  /eslint-visitor-keys/3.3.0:
    eslint-visitor-keys: public
  /eslint/8.29.0:
    eslint: public
  /espree/9.4.1:
    espree: private
  /esprima/4.0.1:
    esprima: private
  /esquery/1.4.0:
    esquery: private
  /esrecurse/4.3.0:
    esrecurse: private
  /estraverse/5.3.0:
    estraverse: private
  /esutils/2.0.3:
    esutils: private
  /fast-deep-equal/3.1.3:
    fast-deep-equal: private
  /fast-glob/3.2.7:
    fast-glob: private
  /fast-json-stable-stringify/2.1.0:
    fast-json-stable-stringify: private
  /fast-levenshtein/2.0.6:
    fast-levenshtein: private
  /fastq/1.14.0:
    fastq: private
  /figures/3.2.0:
    figures: private
  /file-entry-cache/6.0.1:
    file-entry-cache: private
  /filelist/1.0.4:
    filelist: private
  /fill-range/7.0.1:
    fill-range: private
  /find-up/5.0.0:
    find-up: private
  /flat-cache/3.0.4:
    flat-cache: private
  /flat/5.0.2:
    flat: private
  /flatted/3.2.7:
    flatted: private
  /follow-redirects/1.15.2:
    follow-redirects: private
  /form-data/4.0.0:
    form-data: private
  /fs-constants/1.0.0:
    fs-constants: private
  /fs-extra/10.1.0:
    fs-extra: private
  /fs.realpath/1.0.0:
    fs.realpath: private
  /fsevents/2.3.2:
    fsevents: private
  /get-caller-file/2.0.5:
    get-caller-file: private
  /glob-parent/6.0.2:
    glob-parent: private
  /glob/7.1.4:
    glob: private
  /globals/13.18.0:
    globals: private
  /graceful-fs/4.2.10:
    graceful-fs: private
  /grapheme-splitter/1.0.4:
    grapheme-splitter: private
  /has-flag/4.0.0:
    has-flag: private
  /ieee754/1.2.1:
    ieee754: private
  /ignore/5.2.1:
    ignore: private
  /import-fresh/3.3.0:
    import-fresh: private
  /imurmurhash/0.1.4:
    imurmurhash: private
  /inflight/1.0.6:
    inflight: private
  /inherits/2.0.4:
    inherits: private
  /is-binary-path/2.1.0:
    is-binary-path: private
  /is-docker/2.2.1:
    is-docker: private
  /is-extglob/2.1.1:
    is-extglob: private
  /is-fullwidth-code-point/3.0.0:
    is-fullwidth-code-point: private
  /is-glob/4.0.3:
    is-glob: private
  /is-number/7.0.0:
    is-number: private
  /is-path-inside/3.0.3:
    is-path-inside: private
  /is-wsl/2.2.0:
    is-wsl: private
  /isexe/2.0.0:
    isexe: private
  /jake/10.8.5:
    jake: private
  /js-sdsl/4.2.0:
    js-sdsl: private
  /js-tokens/4.0.0:
    js-tokens: private
  /js-yaml/4.1.0:
    js-yaml: private
  /json-schema-traverse/0.4.1:
    json-schema-traverse: private
  /json-stable-stringify-without-jsonify/1.0.1:
    json-stable-stringify-without-jsonify: private
  /json5/1.0.1:
    json5: private
  /jsonc-parser/3.2.0:
    jsonc-parser: private
  /jsonfile/6.1.0:
    jsonfile: private
  /levn/0.4.1:
    levn: private
  /locate-path/6.0.0:
    locate-path: private
  /lodash.merge/4.6.2:
    lodash.merge: private
  /loose-envify/1.4.0:
    loose-envify: private
  /lru-cache/6.0.0:
    lru-cache: private
  /merge2/1.4.1:
    merge2: private
  /micromatch/4.0.5:
    micromatch: private
  /mime-db/1.52.0:
    mime-db: private
  /mime-types/2.1.35:
    mime-types: private
  /mimic-fn/2.1.0:
    mimic-fn: private
  /minimatch/3.1.2:
    minimatch: private
  /minimist/1.2.7:
    minimist: private
  /ms/2.1.2:
    ms: private
  /natural-compare/1.4.0:
    natural-compare: private
  /node-addon-api/3.2.1:
    node-addon-api: private
  /node-gyp-build/4.5.0:
    node-gyp-build: private
  /normalize-path/3.0.0:
    normalize-path: private
  /npm-run-path/4.0.1:
    npm-run-path: private
  /nx/15.3.0:
    nx: private
  /once/1.4.0:
    once: private
  /onetime/5.1.2:
    onetime: private
  /open/8.4.0:
    open: private
  /optionator/0.9.1:
    optionator: private
  /p-limit/3.1.0:
    p-limit: private
  /p-locate/5.0.0:
    p-locate: private
  /parent-module/1.0.1:
    parent-module: private
  /path-exists/4.0.0:
    path-exists: private
  /path-is-absolute/1.0.1:
    path-is-absolute: private
  /path-key/3.1.1:
    path-key: private
  /picomatch/2.3.1:
    picomatch: private
  /prelude-ls/1.2.1:
    prelude-ls: private
  /proxy-from-env/1.1.0:
    proxy-from-env: private
  /punycode/2.1.1:
    punycode: private
  /queue-microtask/1.2.3:
    queue-microtask: private
  /readable-stream/3.6.0:
    readable-stream: private
  /readdirp/3.6.0:
    readdirp: private
  /regexpp/3.2.0:
    regexpp: private
  /require-directory/2.1.1:
    require-directory: private
  /resolve-from/4.0.0:
    resolve-from: private
  /restore-cursor/3.1.0:
    restore-cursor: private
  /reusify/1.0.4:
    reusify: private
  /rimraf/3.0.2:
    rimraf: private
  /run-parallel/1.2.0:
    run-parallel: private
  /safe-buffer/5.2.1:
    safe-buffer: private
  /semver/7.3.4:
    semver: private
  /shebang-command/2.0.0:
    shebang-command: private
  /shebang-regex/3.0.0:
    shebang-regex: private
  /signal-exit/3.0.7:
    signal-exit: private
  /sprintf-js/1.0.3:
    sprintf-js: private
  /string-width/4.2.3:
    string-width: private
  /string_decoder/1.3.0:
    string_decoder: private
  /strip-ansi/6.0.1:
    strip-ansi: private
  /strip-bom/3.0.0:
    strip-bom: private
  /strip-json-comments/3.1.1:
    strip-json-comments: private
  /strong-log-transformer/2.1.0:
    strong-log-transformer: private
  /supports-color/7.2.0:
    supports-color: private
  /tar-stream/2.2.0:
    tar-stream: private
  /text-table/0.2.0:
    text-table: private
  /through/2.3.8:
    through: private
  /tmp/0.2.1:
    tmp: private
  /to-regex-range/5.0.1:
    to-regex-range: private
  /tsconfig-paths/3.14.1:
    tsconfig-paths: private
  /tslib/2.4.1:
    tslib: private
  /type-check/0.4.0:
    type-check: private
  /type-fest/0.20.2:
    type-fest: private
  /universalify/2.0.0:
    universalify: private
  /uri-js/4.4.1:
    uri-js: private
  /util-deprecate/1.0.2:
    util-deprecate: private
  /v8-compile-cache/2.3.0:
    v8-compile-cache: private
  /which/2.0.2:
    which: private
  /word-wrap/1.2.3:
    word-wrap: private
  /wrap-ansi/7.0.0:
    wrap-ansi: private
  /wrappy/1.0.2:
    wrappy: private
  /y18n/5.0.8:
    y18n: private
  /yallist/4.0.0:
    yallist: private
  /yargs-parser/21.1.1:
    yargs-parser: private
  /yocto-queue/0.1.0:
    yocto-queue: private
included:
  dependencies: true
  devDependencies: true
  optionalDependencies: true
injectedDeps: {}
layoutVersion: 5
nodeLinker: isolated
packageManager: pnpm@7.16.0
pendingBuilds: []
prunedAt: Thu, 29 Dec 2022 15:57:57 GMT
publicHoistPattern:
  - '*eslint*'
  - '*prettier*'
registries:
  default: https://registry.npmjs.org/
skipped: []
storeDir: /Users/jdoe/Library/pnpm/store/v3
virtualStoreDir: .pnpm
`;
