use color_eyre::eyre::Result;
use ratatui::{
    Frame,
    layout::{Alignment, Rect},
    style::{Modifier, Style},
    text::{Line, Span},
    widgets::{Block, BorderType, Borders, Clear, Padding},
};
use std::any::Any;

use crate::native::tui::components::nx_paragraph::{NxParagraph, NxText};
use crate::native::tui::theme::THEME;

use super::connect_flow::ConnectFlowState;
use super::link::LinkRegistry;
use super::{Component, ModalPopup};

const MIN_POPUP_WIDTH: u16 = 60;
const MAX_POPUP_WIDTH: u16 = 100;

/// Popup dedicated to connecting the workspace to Nx Cloud. Displays the short
/// onboarding URL generated by the same logic as `nx connect`; Enter opens it
/// in the browser, Esc dismisses.
///
/// The URL arrives asynchronously from JS after the user presses the connect
/// shortcut, so the popup opens in `Loading` and is mutated in place. The state
/// is mirrored in `TuiState`, which is what a rebuilt popup re-hydrates from
/// after a mode switch.
pub struct ConnectPopup {
    visible: bool,
    state: ConnectFlowState,
    /// Screen rect of the bordered popup box from the last render, used for
    /// click-outside-to-dismiss hit-testing.
    last_area: Option<Rect>,
    /// Screen rect of the inner text area (inside the border) from the last
    /// render, used to bound text selection and make the URL clickable.
    content_area: Option<Rect>,
    /// The URL rendered as a curated [`Link`](super::link::Link) recorded here,
    /// so a click opens the full href even when the URL wraps across rows (the
    /// raw row-by-row URL scan would only see one row's fragment).
    link_registry: LinkRegistry,
}

impl ConnectPopup {
    pub fn new() -> Self {
        Self {
            visible: false,
            state: ConnectFlowState::NotStarted,
            last_area: None,
            content_area: None,
            link_registry: LinkRegistry::new(),
        }
    }

    pub fn show(&mut self) {
        self.visible = true;
    }

    pub fn hide(&mut self) {
        self.visible = false;
    }

    pub fn state(&self) -> &ConnectFlowState {
        &self.state
    }

    /// Restore the state persisted in `TuiState` (mode-switch rehydration, and
    /// pushes that arrived from JS while another mode was active).
    pub fn set_state(&mut self, state: ConnectFlowState) {
        self.state = state;
    }

    pub fn render(&mut self, f: &mut Frame<'_>, area: Rect) {
        // Prevent rendering outside buffer bounds (mid-resize frames).
        if area.height == 0
            || area.width == 0
            || area.x >= f.area().width
            || area.y >= f.area().height
        {
            return;
        }

        let safe_area = Rect {
            x: area.x,
            y: area.y,
            width: area.width.min(f.area().width.saturating_sub(area.x)),
            height: area.height.min(f.area().height.saturating_sub(area.y)),
        };

        // Cleared and repopulated on every render (the app also clears it at
        // the start of each draw pass).
        self.link_registry.clear();

        let content = self.state.detail_lines();

        // Size the popup to fit the URL on a single line when possible.
        let max_line_width = content.iter().map(|l| l.width()).max().unwrap_or(0);
        // Border (2) + proportional padding (2 per side horizontally).
        let horizontal_overhead: u16 = 2 + 4;
        let popup_width = (max_line_width + horizontal_overhead)
            .clamp(MIN_POPUP_WIDTH, MAX_POPUP_WIDTH)
            .min(safe_area.width.saturating_sub(2));
        let inner_width = popup_width.saturating_sub(horizontal_overhead).max(1);

        // Account for lines that wrap within the inner width, using the same
        // layout logic the paragraph renders with.
        let content_text: NxText = content.into();
        let content_height = content_text.wrapped_rows(inner_width, false).max(1) as u16;
        // Border (2) + proportional padding (1 per side vertically).
        let popup_height = (content_height + 4).min(safe_area.height.saturating_sub(2));

        let popup_x = safe_area.x + (safe_area.width.saturating_sub(popup_width)) / 2;
        let popup_y = safe_area.y + (safe_area.height.saturating_sub(popup_height)) / 2;
        let popup_area = Rect::new(popup_x, popup_y, popup_width, popup_height);

        // Record the popup box so the app can hit-test mouse events against it.
        self.last_area = Some(popup_area);

        // Bottom border hints, mirroring the other popups.
        let mut hint_spans = vec![Span::styled("  ", Style::default())];
        if self.state.url().is_some() {
            hint_spans.extend([
                Span::styled("open in browser: ", Style::default().fg(THEME.secondary_fg)),
                Span::styled("<enter>", Style::default().fg(THEME.info)),
                Span::styled("  ", Style::default()),
            ]);
        }
        hint_spans.extend([
            Span::styled("close: ", Style::default().fg(THEME.secondary_fg)),
            Span::styled("<esc>", Style::default().fg(THEME.info)),
            Span::styled("  ", Style::default()),
        ]);
        let dismiss_hint = Line::from(hint_spans);

        let block = Block::default()
            .title(Line::from(vec![
                Span::raw("  "),
                Span::styled(
                    " NX ",
                    Style::default()
                        .add_modifier(Modifier::BOLD)
                        .bg(THEME.info)
                        .fg(THEME.primary_fg),
                ),
                Span::styled("  Connect to Nx Cloud  ", Style::default().fg(THEME.info)),
            ]))
            .title_alignment(Alignment::Left)
            .title_bottom(dismiss_hint.alignment(Alignment::Right))
            .borders(Borders::ALL)
            .border_type(BorderType::Plain)
            .border_style(Style::default().fg(THEME.info))
            .padding(Padding::proportional(1));

        // The text area sits inside the border + padding.
        self.content_area = Some(block.inner(popup_area));

        let popup = NxParagraph::new(content_text)
            .block(block)
            .wrap(ratatui::widgets::Wrap { trim: false });

        f.render_widget(Clear, popup_area);
        // Stateful render records the URL link's screen rects into the
        // registry for mouse hit-testing.
        f.render_stateful_widget(popup, popup_area, &mut self.link_registry);
    }
}

impl Default for ConnectPopup {
    fn default() -> Self {
        Self::new()
    }
}

impl Component for ConnectPopup {
    fn draw(&mut self, f: &mut Frame<'_>, rect: Rect) -> Result<()> {
        if self.visible {
            self.render(f, rect);
        } else {
            self.last_area = None;
            self.content_area = None;
        }
        Ok(())
    }

    fn link_registry(&self) -> Option<&LinkRegistry> {
        Some(&self.link_registry)
    }

    fn link_registry_mut(&mut self) -> Option<&mut LinkRegistry> {
        Some(&mut self.link_registry)
    }

    fn as_any(&self) -> &dyn Any {
        self
    }

    fn as_any_mut(&mut self) -> &mut dyn Any {
        self
    }
}

impl ModalPopup for ConnectPopup {
    fn is_visible(&self) -> bool {
        self.visible
    }

    fn last_area(&self) -> Option<Rect> {
        self.last_area
    }

    fn content_area(&self) -> Option<Rect> {
        self.content_area
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use ratatui::Terminal;
    use ratatui::backend::TestBackend;

    fn render_to_string(popup: &mut ConnectPopup) -> String {
        let mut terminal = Terminal::new(TestBackend::new(110, 20)).unwrap();
        terminal
            .draw(|f| {
                let area = f.area();
                popup.render(f, area);
            })
            .unwrap();
        let buffer = terminal.backend().buffer().clone();
        (0..buffer.area.height)
            .map(|y| {
                (0..buffer.area.width)
                    .map(|x| buffer.cell((x, y)).unwrap().symbol().to_string())
                    .collect::<String>()
            })
            .collect::<Vec<_>>()
            .join("\n")
    }

    #[test]
    fn shows_a_spinner_message_until_the_url_arrives() {
        let mut popup = ConnectPopup::new();
        popup.set_state(ConnectFlowState::Loading);
        let text = render_to_string(&mut popup);
        assert!(
            text.contains("Generating your Nx Cloud connect URL"),
            "{text}"
        );
        // Nothing to open yet.
        assert!(!text.contains("open in browser"), "{text}");
    }

    #[test]
    fn offers_the_url_and_the_browser_hint_when_ready() {
        let mut popup = ConnectPopup::new();
        popup.set_state(ConnectFlowState::Ready("https://nx.app/c/abc".to_string()));
        let text = render_to_string(&mut popup);
        assert!(text.contains("https://nx.app/c/abc"), "{text}");
        assert!(text.contains("open in browser: <enter>"), "{text}");
    }

    #[test]
    fn surfaces_the_failure_and_the_retry_path() {
        let mut popup = ConnectPopup::new();
        popup.set_state(ConnectFlowState::Error("no git remote".to_string()));
        let text = render_to_string(&mut popup);
        assert!(text.contains("Could not connect to Nx Cloud."), "{text}");
        assert!(text.contains("no git remote"), "{text}");
        assert!(text.contains("<shift>+c"), "{text}");
    }
}
