use color_eyre::eyre::Result;
use ratatui::{
    Frame,
    layout::{Alignment, Rect},
    style::{Modifier, Style},
    text::{Line, Span},
    widgets::{Block, BorderType, Borders, Clear, Padding},
};
use std::any::Any;

use crate::native::tui::components::nx_paragraph::NxParagraph;
use crate::native::tui::theme::THEME;

use super::Component;

const MIN_POPUP_WIDTH: u16 = 60;
const MAX_POPUP_WIDTH: u16 = 100;

/// Content of the connect popup. The URL arrives asynchronously from JS after
/// the user presses the connect shortcut, so the popup opens in `Loading` and
/// is mutated in place (popups rebuild their content from state every frame).
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ConnectPopupState {
    /// No connect attempt has been made yet.
    NotStarted,
    /// JS is creating the workspace / generating the onboarding URL.
    Loading,
    /// The onboarding URL is ready to follow.
    Ready(String),
    /// The connect attempt failed (e.g. offline, missing git remote).
    Error(String),
}

/// Popup shown when the user connects to Nx Cloud from the TUI. Displays the
/// short onboarding URL generated by the same logic as `nx connect`; Enter
/// opens it in the browser, Esc dismisses.
pub struct ConnectPopup {
    visible: bool,
    state: ConnectPopupState,
    /// Screen rect of the bordered popup box from the last render, used for
    /// click-outside-to-dismiss hit-testing.
    last_area: Option<Rect>,
    /// Screen rect of the inner text area (inside the border) from the last
    /// render, used to bound text selection and make the URL clickable.
    content_area: Option<Rect>,
}

impl ConnectPopup {
    pub fn new() -> Self {
        Self {
            visible: false,
            state: ConnectPopupState::NotStarted,
            last_area: None,
            content_area: None,
        }
    }

    /// The bordered popup box drawn last frame, if visible.
    pub fn last_area(&self) -> Option<Rect> {
        self.last_area
    }

    /// The inner text area drawn last frame, if visible.
    pub fn content_area(&self) -> Option<Rect> {
        self.content_area
    }

    pub fn show(&mut self) {
        self.visible = true;
    }

    pub fn hide(&mut self) {
        self.visible = false;
    }

    pub fn is_visible(&self) -> bool {
        self.visible
    }

    /// Whether a new connect attempt should be started when the popup opens.
    /// A `Ready` URL is kept (reopening shows it again without re-connecting);
    /// an `Error` allows a retry.
    pub fn needs_connect_attempt(&self) -> bool {
        matches!(
            self.state,
            ConnectPopupState::NotStarted | ConnectPopupState::Error(_)
        )
    }

    pub fn set_loading(&mut self) {
        self.state = ConnectPopupState::Loading;
    }

    pub fn set_url(&mut self, url: String) {
        self.state = ConnectPopupState::Ready(url);
    }

    pub fn set_error(&mut self, message: String) {
        self.state = ConnectPopupState::Error(message);
    }

    /// The onboarding URL, once the connect attempt succeeded.
    pub fn url(&self) -> Option<&str> {
        match &self.state {
            ConnectPopupState::Ready(url) => Some(url),
            _ => None,
        }
    }

    pub fn state(&self) -> &ConnectPopupState {
        &self.state
    }

    fn content_lines(&self) -> Vec<Line<'static>> {
        let primary = Style::default().fg(THEME.primary_fg);
        match &self.state {
            ConnectPopupState::NotStarted | ConnectPopupState::Loading => {
                vec![Line::from(Span::styled(
                    "Generating your Nx Cloud connect URL...",
                    primary,
                ))]
            }
            ConnectPopupState::Ready(url) => vec![
                Line::from(Span::styled(
                    "Follow this link to finish connecting your workspace to Nx Cloud.",
                    primary,
                )),
                Line::from(Span::styled("The setup takes about 2 minutes:", primary)),
                Line::from(""),
                Line::from(Span::styled(url.clone(), Style::default().fg(THEME.info))),
            ],
            ConnectPopupState::Error(message) => vec![
                Line::from(Span::styled(
                    "Could not connect to Nx Cloud.",
                    Style::default().fg(THEME.error),
                )),
                Line::from(""),
                Line::from(Span::styled(message.clone(), primary)),
                Line::from(""),
                Line::from(vec![
                    Span::styled("Press ", Style::default().fg(THEME.secondary_fg)),
                    Span::styled("C", Style::default().fg(THEME.info)),
                    Span::styled(
                        " to try again, or run `nx connect` in your terminal.",
                        Style::default().fg(THEME.secondary_fg),
                    ),
                ]),
            ],
        }
    }

    pub fn render(&mut self, f: &mut Frame<'_>, area: Rect) {
        // Prevent rendering outside buffer bounds (mid-resize frames).
        if area.height == 0
            || area.width == 0
            || area.x >= f.area().width
            || area.y >= f.area().height
        {
            return;
        }

        let safe_area = Rect {
            x: area.x,
            y: area.y,
            width: area.width.min(f.area().width.saturating_sub(area.x)),
            height: area.height.min(f.area().height.saturating_sub(area.y)),
        };

        let content = self.content_lines();

        // Size the popup to fit the URL on a single line when possible, so the
        // raw-URL click detection (which scans row by row) sees the whole URL.
        let max_line_width = content.iter().map(|l| l.width()).max().unwrap_or(0) as u16;
        // Border (2) + proportional padding (2 per side horizontally).
        let horizontal_overhead: u16 = 2 + 4;
        let popup_width = (max_line_width + horizontal_overhead)
            .clamp(MIN_POPUP_WIDTH, MAX_POPUP_WIDTH)
            .min(safe_area.width.saturating_sub(2));
        let inner_width = popup_width.saturating_sub(horizontal_overhead).max(1);

        // Account for lines that wrap within the inner width.
        let content_height: u16 = content
            .iter()
            .map(|l| (l.width() as u16).div_ceil(inner_width).max(1))
            .sum();
        // Border (2) + proportional padding (1 per side vertically).
        let popup_height = (content_height + 4).min(safe_area.height.saturating_sub(2));

        let popup_x = safe_area.x + (safe_area.width.saturating_sub(popup_width)) / 2;
        let popup_y = safe_area.y + (safe_area.height.saturating_sub(popup_height)) / 2;
        let popup_area = Rect::new(popup_x, popup_y, popup_width, popup_height);

        // Record the popup box so the app can hit-test mouse events against it.
        self.last_area = Some(popup_area);

        // Bottom border hints, mirroring the other popups.
        let mut hint_spans = vec![Span::styled("  ", Style::default())];
        if matches!(self.state, ConnectPopupState::Ready(_)) {
            hint_spans.extend([
                Span::styled("open in browser: ", Style::default().fg(THEME.secondary_fg)),
                Span::styled("<enter>", Style::default().fg(THEME.info)),
                Span::styled("  ", Style::default()),
            ]);
        }
        hint_spans.extend([
            Span::styled("close: ", Style::default().fg(THEME.secondary_fg)),
            Span::styled("<esc>", Style::default().fg(THEME.info)),
            Span::styled("  ", Style::default()),
        ]);
        let dismiss_hint = Line::from(hint_spans);

        let block = Block::default()
            .title(Line::from(vec![
                Span::raw("  "),
                Span::styled(
                    " NX ",
                    Style::default()
                        .add_modifier(Modifier::BOLD)
                        .bg(THEME.info)
                        .fg(THEME.primary_fg),
                ),
                Span::styled("  Connect to Nx Cloud  ", Style::default().fg(THEME.info)),
            ]))
            .title_alignment(Alignment::Left)
            .title_bottom(dismiss_hint.alignment(Alignment::Right))
            .borders(Borders::ALL)
            .border_type(BorderType::Plain)
            .border_style(Style::default().fg(THEME.info))
            .padding(Padding::proportional(1));

        // The text area sits inside the border + padding.
        self.content_area = Some(block.inner(popup_area));

        let popup = NxParagraph::new(content)
            .block(block)
            .wrap(ratatui::widgets::Wrap { trim: false });

        f.render_widget(Clear, popup_area);
        f.render_widget(popup, popup_area);
    }
}

impl Default for ConnectPopup {
    fn default() -> Self {
        Self::new()
    }
}

impl Component for ConnectPopup {
    fn draw(&mut self, f: &mut Frame<'_>, rect: Rect) -> Result<()> {
        if self.visible {
            self.render(f, rect);
        } else {
            self.last_area = None;
            self.content_area = None;
        }
        Ok(())
    }

    fn as_any(&self) -> &dyn Any {
        self
    }

    fn as_any_mut(&mut self) -> &mut dyn Any {
        self
    }
}
