import { NormalizedPackageJson } from './pruning-utils';
import { YarnDependency } from './types';

export const BERRY_LOCK_FILE_DISCLAIMER = `# This file was generated by Nx. Do not edit this file directly\n# Manual changes might be lost - proceed with caution!\n\n`;

export function generateRootWorkspacePackage(
  packageJson: NormalizedPackageJson
): YarnDependency {
  return {
    version: '0.0.0-use.local',
    resolution: `${packageJson.name}@workspace:.`,
    ...(packageJson.dependencies && { dependencies: packageJson.dependencies }),
    ...(packageJson.peerDependencies && {
      peerDependencies: packageJson.peerDependencies,
    }),
    ...(packageJson.devDependencies && {
      devDependencies: packageJson.devDependencies,
    }),
    ...(packageJson.optionalDependencies && {
      optionalDependencies: packageJson.optionalDependencies,
    }),
    languageName: 'unknown',
    linkType: 'soft',
  };
}

export function isTarballDependency({
  version,
  resolution,
}: YarnDependency): boolean {
  // for tarball packages version might not exist or be useless
  if (!version || (resolution && !resolution.includes(version))) {
    return true;
  }
}

export function isAliasDependency(version: string): boolean {
  return version.startsWith('npm:');
}
