exclude-reads:
  - 'dist/target/**'
exclude-writes:
  - '**/.swc/**'
  - 'dist/target/**'

task-exclusions:
  - target: lint
    exclude-reads:
      - '**/dist/**/*.json'
  - project: graph-client
    target: build-client
    exclude-reads:
      - '**/*.stories.{js,jsx,ts,tsx,mdx}'
      - '**/*.{spec,test}.{js,jsx,ts,tsx}'
