/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Gradle plugin project to get you started.
 * For more details on writing Custom Plugins, please refer to https://docs.gradle.org/8.5/userguide/custom_plugins.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    // Apply the Java Gradle plugin development plugin to add support for developing Gradle plugins
    `java-gradle-plugin`
    `maven-publish`

    // Apply the Kotlin JVM plugin to add support for Kotlin.
    alias(libs.plugins.jvm)
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

gradlePlugin {
    // Define the plugin
    val Nodes by plugins.creating {
        id = "io.nx.gradle.plugin.Nodes"
        implementationClass = "io.nx.gradle.plugin.Nodes"
    }
}

dependencies {
  implementation("com.google.code.gson:gson:2.11.0")
}
