export function NxUsersShowcase() {
  return (
    <div className="max-w-screen-lg mx-auto px-5 py-32">
      <p className="sm:mx-auto sm:text-lg">Join the ecosystem of Nx users</p>
      <div className="mt-12 grid items-center justify-items-center grid-cols-3 md:grid-cols-6 gap-12">
        <img
          className="opacity-60"
          src="/images/nx-users/Accenture.png"
          width={130}
          height={45}
        />
        <img
          className="opacity-60"
          src="/images/nx-users/AmericanAirlines.png"
          width={140}
          height={50}
        />
        <img
          className="opacity-60"
          src="/images/nx-users/AmericanTireDistributors.png"
          width={80}
          height={50}
        />
        <img
          className="opacity-60"
          src="/images/nx-users/Anthem.png"
          width={95}
          height={80}
        />
        <img
          className="opacity-60"
          src="/images/nx-users/Audi.png"
          width={60}
          height={50}
        />
        <img
          className="opacity-60"
          src="/images/nx-users/BlackRock.png"
          width={100}
          height={50}
        />
        <img
          className="opacity-60"
          src="/images/nx-users/CapitalOne.png"
          width={95}
          height={50}
        />
        <img
          className="opacity-60"
          src="/images/nx-users/Cigna.png"
          width={100}
          height={50}
        />
        <img
          className="opacity-60"
          src="/images/nx-users/Cisco.png"
          width={70}
          height={50}
        />
        <img
          className="opacity-60"
          src="/images/nx-users/Datasite.png"
          width={100}
          height={50}
        />
        <img
          className="opacity-60"
          src="/images/nx-users/FedEx.png"
          width={95}
          height={50}
        />
        <img
          className="opacity-60"
          src="/images/nx-users/FICO.png"
          width={65}
          height={50}
        />
        <img
          className="opacity-60"
          src="/images/nx-users/GM.png"
          width={40}
          height={50}
        />
        <img
          className="opacity-60"
          src="/images/nx-users/Microsoft.png"
          width={85}
          height={50}
        />
        <img
          className="opacity-60"
          src="/images/nx-users/RedHat.png"
          width={110}
          height={50}
        />
        <img
          className="opacity-60"
          src="/images/nx-users/SatcomDirect.png"
          width={75}
          height={50}
        />
        <img
          className="opacity-60"
          src="/images/nx-users/TMobile.png"
          width={125}
          height={50}
        />
        <img
          className="opacity-60"
          src="/images/nx-users/Viacom.png"
          width={95}
          height={50}
        />
      </div>
    </div>
  );
}

export default NxUsersShowcase;
