// @ts-check
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';
import { sectionSidebarPlugin } from './src/plugins/section-sidebar.plugin';
import netlify from '@astrojs/netlify';
import linkValidator from 'starlight-links-validator';
import react from '@astrojs/react';
import markdoc from '@astrojs/markdoc';
import tailwindcss from '@tailwindcss/vite';

// https://astro.build/config
export default defineConfig({
  vite: { plugins: [tailwindcss()] },
  site: 'https://docs.nx.dev',
  adapter: netlify(),
  integrations: [
    markdoc(),
    starlight({
      title: 'Nx',
      tagline:
        'An AI-first build platform that connects everything from your editor to CI. Helping you deliver fast, without breaking things.',
      customCss: ['./src/styles/global.css'],
      favicon: '/favicon.svg',
      logo: {
        src: './src/assets/nx/Nx-light.png',
        replacesTitle: true,
      },
      plugins: [
        // linkValidator(),
        sectionSidebarPlugin(),
      ],
      routeMiddleware: ['./src/plugins/banner.middleware.ts'],
      markdown: {
        // this breaks the renderMarkdown function in the plugin loader due to starlight path normalization
        // as to _why_ it has to normalize a path?
        // idk just working around the issue for now but we'll want to have linked headers so will need to fix
        headingLinks: false,
      },
      social: [
        { icon: 'github', label: 'GitHub', href: 'https://github.com/nrwl/nx' },
        {
          icon: 'youtube',
          label: 'YouTube',
          href: 'https://www.youtube.com/@NxDevtools?utm_source=nx.dev',
        },
        {
          icon: 'x.com',
          label: 'X',
          href: 'https://x.com/NxDevTools?utm_source=nx.dev',
        },
        {
          icon: 'discord',
          label: 'Discord',
          href: 'https://go.nx.dev/community',
        },
      ],
      editLink: {
        baseUrl: 'https://github.com/nrwl/nx/tree/main/',
      },
      sidebar: [
        {
          label: 'Getting Started',
          autogenerate: { directory: 'getting-started' },
        },
        {
          label: 'Guides',
          autogenerate: { directory: 'guides' },
        },
        {
          label: 'Concepts',
          autogenerate: { directory: 'concepts' },
        },
        {
          label: 'References',
          collapsed: true,
          items: [
            // have to use link bc slug is mapped to the /docs/ folder but we need the astro component in the pages/ dir
            { label: 'Nx CLI', link: 'api/nx-cli' },
            { label: 'Nx Cloud CLI', slug: 'api/nx-cloud-cli' },
            { label: 'create-nx-workspace', link: 'api/create-nx-workspace' },
            {
              label: 'devkit',
              collapsed: true,
              items: [
                { label: 'Overview', link: 'api/plugins/devkit/' },
                {
                  label: 'Ng CLI Adapter',
                  link: 'api/plugins/devkit/ngcli_adapter',
                },
              ],
            },
            // plugins are autogenerated from the Nx repository via the sidebar plugin
          ],
        },
      ],
    }),
    react(),
  ],
});
