import { CreateDependencies, logger } from '@nx/devkit';
import { getCachedMavenData } from './maven-data-cache';

/**
 * Create dependencies between Maven projects by analyzing the createNodesResults
 * Uses cached Maven analysis data that was generated by createNodesV2
 */
export const createDependencies: CreateDependencies = (_options, context) => {
  // Get cached Maven analysis data that was generated by createNodesV2
  const mavenData = getCachedMavenData(context.workspaceRoot);
  if (!mavenData) {
    logger.verbose(
      '[Maven Dependencies] No Maven data found in workspace:',
      context.workspaceRoot
    );
    return [];
  }

  logger.verbose(
    '[Maven Dependencies] Found Maven data with',
    mavenData.createDependenciesResults.length,
    'dependencies'
  );

  // Extract dependencies from the mavenData
  return mavenData.createDependenciesResults;
};
