export { getOutputsForTargetAndConfiguration } from '@nx/devkit';
export {
  DependsOnEntryLocation,
  NormalizedTargetDependencyConfig,
  calculateReverseDeps,
  createTaskId,
  expandDependencyConfigSyntaxSugar,
  expandInitiatingTasksThroughNoop,
  expandWildcardTargetConfiguration,
  getCliPath,
  getCustomHasher,
  getDependencyConfigs,
  getExecutorForTask,
  getExecutorNameForTask,
  getOutputs,
  getPrintableCommandArgsForTask,
  getSerializedArgsForTask,
  getTargetConfigurationForTask,
  getUnparsedOverrideArgs,
  interpolate,
  isCacheableTask,
  normalizeDependencyConfigDefinition,
  normalizeDependencyConfigProjects,
  normalizeTargetDependencyWithStringProjects,
  readProjectAndTargetFromTargetString,
  removeTasksFromTaskGraph,
  shouldStreamOutput,
  transformLegacyOutputs,
  unparse,
  validateOutputs,
} from '@nx/devkit/internal';
