package dev.nx.maven.runner

import org.apache.maven.api.model.Model
import org.apache.maven.impl.resolver.MavenWorkspaceReader
import org.apache.maven.project.MavenProject
import org.eclipse.aether.artifact.Artifact
import org.eclipse.aether.repository.WorkspaceRepository
import org.slf4j.LoggerFactory
import java.io.File

/**
 * Workspace reader that provides access to artifacts from reactor projects.
 * This allows Maven Resolver to find artifacts that are being built in the current build
 * without requiring them to be in the local repository.
 *
 * Particularly important for consumer POM validation during install phase,
 * where Maven needs to resolve the artifact descriptor for the artifact being installed.
 */
class ReactorWorkspaceReader(
    private val projects: Collection<MavenProject>
) : MavenWorkspaceReader {
    private val log = LoggerFactory.getLogger(ReactorWorkspaceReader::class.java)
    private val repository = WorkspaceRepository("reactor", ReactorKey(projects))

    init {
        log.info("🔧 ReactorWorkspaceReader initialized with ${projects.size} projects:")
        projects.forEach { project ->
            log.info("   - ${project.groupId}:${project.artifactId}:${project.version}")
        }
    }

    override fun getRepository(): WorkspaceRepository = repository

    /**
     * Find an artifact file from the reactor projects.
     *
     * For POM artifacts with no classifier, returns the consumer POM if available,
     * otherwise returns the main artifact.
     * For other artifacts, returns the main artifact or attached artifact matching the classifier.
     */
    override fun findArtifact(artifact: Artifact): File? {
        log.info("🔍🔍🔍 ReactorWorkspaceReader.findArtifact() CALLED: $artifact (extension=${artifact.extension}, classifier=${artifact.classifier})")

        val project = findProject(artifact)
        if (project == null) {
            log.debug("   ❌ No matching project found for $artifact")
            return null
        }

        log.debug("   ✓ Found project: ${project.groupId}:${project.artifactId}:${project.version}")

        // For POM artifacts, look for consumer POM first, then fall back to project POM
        if (artifact.extension == "pom" && artifact.classifier.isEmpty()) {
            log.debug("   📄 Looking for consumer POM (POM artifact with no classifier)...")
            val consumerPom = findConsumerPom(project)
            if (consumerPom != null) {
                log.info("   ✅ Found consumer POM for $artifact at ${consumerPom.absolutePath}")
                return consumerPom
            }
            log.debug("   ℹ️  No consumer POM found, checking for main project POM...")

            // If no consumer POM, return the project's main POM file
            val projectPom = project.file
            if (projectPom != null && projectPom.exists()) {
                log.info("   ✅ Found project POM for $artifact at ${projectPom.absolutePath}")
                return projectPom
            }
            log.debug("   ℹ️  No project POM found either")
        }

        // For non-classifier artifacts, return main artifact
        if (artifact.classifier.isEmpty()) {
            log.debug("   🎯 Looking for main artifact (no classifier)...")
            val mainArtifact = project.artifact?.file
            if (mainArtifact != null && mainArtifact.exists()) {
                log.info("   ✅ Found main artifact for $artifact at ${mainArtifact.absolutePath}")
                return mainArtifact
            }
            log.debug("   ℹ️  No main artifact or file doesn't exist")
        }

        // For classifier artifacts, find matching attached artifact
        log.debug("   🏷️  Looking for attached artifact with classifier='${artifact.classifier}' type='${artifact.extension}'...")
        log.debug("   Available attached artifacts: ${project.attachedArtifacts.size}")
        project.attachedArtifacts.forEach { a ->
            log.debug("      - ${a.groupId}:${a.artifactId}:${a.version} classifier='${a.classifier}' type='${a.type}' file=${a.file?.absolutePath}")
        }

        val attachedArtifact = project.attachedArtifacts.find { attached ->
            attached.classifier == artifact.classifier &&
                attached.type == artifact.extension
        }
        if (attachedArtifact != null && attachedArtifact.file != null && attachedArtifact.file.exists()) {
            log.info("   ✅ Found attached artifact for $artifact at ${attachedArtifact.file.absolutePath}")
            return attachedArtifact.file
        }

        log.warn("   ❌ Artifact not found in reactor: $artifact")
        return null
    }

    /**
     * Find the consumer POM for a project.
     * Consumer POMs are generated by Maven during the build and stored as attached artifacts.
     * If not found in attached artifacts, look for them on disk in the target directory.
     */
    private fun findConsumerPom(project: MavenProject): File? {
        log.info("     🔎 Looking for consumer POM in ${project.attachedArtifacts.size} attached artifacts for ${project.groupId}:${project.artifactId}...")
        project.attachedArtifacts.forEach { artifact ->
            val fileName = artifact.file?.name ?: "null"
            val classifier = artifact.classifier ?: "(no classifier)"
            val isConsumerPom = artifact.file != null && artifact.file.name.startsWith("consumer-") && artifact.file.name.endsWith(".pom")
            log.info("       - $fileName (classifier: $classifier): isConsumerPom=$isConsumerPom file exists=${artifact.file?.exists()}")
        }

        // First, check attached artifacts
        val fromAttached = project.attachedArtifacts.find { artifact ->
            // Consumer POMs are temporary files with "consumer-" in the name
            artifact.file != null && artifact.file.name.startsWith("consumer-") &&
                artifact.file.name.endsWith(".pom")
        }?.file

        if (fromAttached != null) {
            log.debug("       ✅ Found consumer POM in attached artifacts: ${fromAttached.absolutePath}")
            return fromAttached
        }

        // If not in attached artifacts, look on disk in target/ directory
        log.debug("     No consumer POM in attached artifacts, checking disk in ${project.build.directory}...")
        val targetDir = File(project.build.directory)
        if (targetDir.exists() && targetDir.isDirectory) {
            val consumerPomFile = targetDir.listFiles { file ->
                file.isFile && file.name.startsWith("consumer-") && file.name.endsWith(".pom")
            }?.firstOrNull()

            if (consumerPomFile != null) {
                log.debug("       ✅ Found consumer POM on disk: ${consumerPomFile.absolutePath}")
                return consumerPomFile
            }
        }

        log.debug("     ❌ No consumer POM found")
        return null
    }

    /**
     * Find the model for an artifact.
     * This is used by Maven to read the POM model from reactor projects.
     */
    override fun findModel(artifact: Artifact): Model? {
        // We can't parse the model here directly without a ModelBuilder,
        // so we return null and let Maven's normal model loading handle it
        // The findArtifact() method above already provides the file,
        // which is what matters for resolution
        return null
    }

    /**
     * Find all versions of an artifact in the reactor.
     */
    override fun findVersions(artifact: Artifact): List<String> {
        return projects
            .filter { project ->
                project.groupId == artifact.groupId &&
                    project.artifactId == artifact.artifactId
            }
            .mapNotNull { it.version }
            .distinct()
    }

    /**
     * Find a project matching the artifact coordinates.
     */
    private fun findProject(artifact: Artifact): MavenProject? {
        return projects.find { project ->
            project.groupId == artifact.groupId &&
                project.artifactId == artifact.artifactId &&
                project.version == artifact.version
        }
    }

    /**
     * Key used to identify this workspace repository.
     */
    private data class ReactorKey(val projects: Collection<MavenProject>) {
        override fun toString(): String = "reactor:${projects.size}-projects"
    }
}
