export const targetOptionsToCliMap = {
  headed: 'headed',
  headless: 'headless',
  key: 'key',
  record: 'record',
  parallel: 'parallel',
  browser: 'browser',
  env: 'env',
  spec: 'spec',
  ciBuildId: 'ci-build-id',
  group: 'group',
  reporter: 'reporter',
  reporterOptions: 'reporter-options',
  tag: 'tag',
  port: 'port',
  quiet: 'quiet',
  runnerUi: 'runner-ui',
};
