import { defineRouteMiddleware } from '@astrojs/starlight/route-data';
/*
 * Using this middleware to insert icons because `attrs` is not valid for sidebar items with children.
 * This also allows us to add icons to autogenerated sidebar items (if needed in the future).
 */

const iconMap: Record<string, string> = {
  TypeScript: 'typescript',
  Angular: 'angular',
  React: 'react',
  Vue: 'vuedotjs',
  'Node.js': 'nodedotjs',
  Java: 'java',
  'Module Federation': 'module-federation',
  ESLint: 'eslint',
  'Build Tools': 'buildtools',
  'Test Tools': 'testtools',
};

function addIconsToSidebar(sidebar: any[]): void {
  sidebar.forEach((entry) => {
    const icon = iconMap[entry.label];

    if (icon) {
      entry.attrs = { ...entry.attrs, 'data-icon': icon };
    }

    if (entry.type === 'group' && entry.entries) {
      addIconsToSidebar(entry.entries);
    }
  });
}

export const onRequest = defineRouteMiddleware(async (context) => {
  const { sidebar } = context.locals.starlightRoute;
  addIconsToSidebar(sidebar);
});
