export const nxPackages = [
  `@nx/angular`,
  `@nx/cypress`,
  `@nx/eslint-plugin`,
  `@nx/express`,
  `@nx/esbuild`,
  `@nx/gradle`,
  `@nx/jest`,
  `@nx/js`,
  `@nx/eslint`,
  `@nx/nest`,
  `@nx/next`,
  `@nx/node`,
  `@nx/nuxt`,
  `@nx/plugin`,
  `@nx/playwright`,
  `@nx/rollup`,
  `@nx/react`,
  `@nx/remix`,
  `@nx/rspack`,
  `@nx/storybook`,
  `@nx/vue`,
  `@nx/vite`,
  `@nx/web`,
  `@nx/webpack`,
  `@nx/react-native`,
  `@nx/expo`,
] as const;
export type NxPackage = (typeof nxPackages)[number];
export type PackageManager = 'npm' | 'yarn' | 'pnpm' | 'bun';
