export default `# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1


"test-cdn-package@https://cdn.test.com/test-cdn-package-0.8.6/test-cdn-package-0.8.6.tgz":
  version "0.19.3"
  resolved "https://cdn.test.com/test-cdn-package-0.8.6/test-cdn-package-0.8.6.tgz"
`;
