import {
  checkFilesExist,
  killProcessAndPorts,
  runCLI,
  runCommandUntil,
  runE2ETests,
  uniq,
} from '@nx/e2e-utils';
import {
  cleanupModuleFederationV2Test,
  setupModuleFederationV2Test,
} from './setup';

describe('@nx/module-federation v2 - Vite', () => {
  beforeAll(() => {
    setupModuleFederationV2Test();
  });

  afterAll(() => cleanupModuleFederationV2Test());

  it('generates a vite provider that serves standalone', async () => {
    const provider = uniq('vite-provider');
    const providerPort = 5101;

    runCLI(
      `generate @nx/react:provider apps/${provider} --bundler=vite --port=${providerPort} --no-interactive --skipFormat`
    );

    checkFilesExist(
      `apps/${provider}/vite.config.ts`,
      `apps/${provider}/index.html`,
      `apps/${provider}/src/index.ts`,
      `apps/${provider}/src/bootstrap.tsx`,
      `apps/${provider}/src/App.tsx`,
      `apps/${provider}/package.json`,
      `apps/${provider}/tsconfig.json`
    );

    if (runE2ETests()) {
      const serve = await runCommandUntil(
        `serve ${provider}`,
        (output) => output.includes('Local:') || output.includes('ready in'),
        { timeout: 120000 }
      );
      await killProcessAndPorts(serve.pid, providerPort);
    }
  }, 600_000);

  it('generates a vite consumer + provider in one shot via --providerNames and wires the manifest', async () => {
    const consumer = uniq('vite-consumer');
    const provider = uniq('vite-provider');
    // Per-bundler defaults: consumer 5100, first generated provider 5101.
    const consumerPort = 5100;
    const providerPort = 5101;

    runCLI(
      `generate @nx/react:consumer apps/${consumer} --bundler=vite --providerNames=${provider} --no-interactive --skipFormat`
    );

    checkFilesExist(
      `apps/${consumer}/vite.config.ts`,
      `apps/${consumer}/src/mf.ts`,
      `apps/${consumer}/src/App.tsx`,
      // Sibling provider auto-generated by --providerNames.
      `apps/${provider}/vite.config.ts`,
      `apps/${provider}/src/App.tsx`
    );

    if (runE2ETests()) {
      // `nx serve <provider>` brings the consumer up via provider.serve.dependsOn.
      // Wait for both Vite "Local:" lines (one per app) to confirm the chain
      // is fully up before killing.
      let consumerReady = false;
      let providerReady = false;
      const serve = await runCommandUntil(
        `serve ${provider}`,
        (output) => {
          if (output.includes(`http://127.0.0.1:${consumerPort}/`)) {
            consumerReady = true;
          }
          if (output.includes(`http://127.0.0.1:${providerPort}/`)) {
            providerReady = true;
          }
          return consumerReady && providerReady;
        },
        { timeout: 180000 }
      );
      await killProcessAndPorts(serve.pid, consumerPort, providerPort);
    }
  }, 900_000);
});
