name: CI

on:
  push:
    branches:
      - master
      - '[0-9]+.[0-9]+.x'
  pull_request:
    branches:
      - "**"

env:
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
  NX_CLOUD_ENABLE_METRICS_COLLECTION: 'true'
  PNPM_HOME: ~/.pnpm

jobs:
  main-linux:
    runs-on: ubuntu-latest
    env:
      NX_BATCH_MODE: 'true'
      NX_E2E_CI_CACHE_KEY: e2e-github-linux
      NX_DAEMON: 'true'
      NX_PERF_LOGGING: 'false'
      NX_VERBOSE_LOGGING: 'false'
      NX_NATIVE_LOGGING: 'false'
      NX_E2E_RUN_E2E: 'true'
      NX_CI_EXECUTION_ENV: 'linux'
      NX_CLOUD_NO_TIMEOUTS: 'true'
      NX_ALLOW_NON_CACHEABLE_DTE: 'true'
      NX_CLOUD_EXPERIMENTAL_POLLING: 'true'
      NX_CLOUD_CONTINUOUS_ASSIGNMENT: 'false'
      NX_CLOUD_VERBOSE_LOGGING: 'true'

    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0
          filter: tree:0

      - name: Fetch Master
        run: git fetch origin master:master
        if: ${{ github.event_name == 'pull_request' }}

      - name: Set SHAs
        uses: nrwl/nx-set-shas@1859e66a83ac9be0dceecbd9a023702e27ac47f4 # v4.3.3
        with:
          main-branch-name: 'master'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ca-certificates lsof libvips-dev libglib2.0-dev libgirepository1.0-dev

      - name: Setup dev tools with mise
        uses: jdx/mise-action@146a28175021df8ca24f8ee1828cc2a60f980bd5 # v3

      - name: Enable corepack and install pnpm
        run: |
          corepack enable
          corepack prepare --activate

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@48b5f213c81028ace310571dc5ec0fbbca0b2947 # v4.4.3

      - name: Install project dependencies
        run: |
          pnpm install --frozen-lockfile

      - name: Nx Report
        run:
          pnpm nx report

      - name: Report Daemon logs
        run:
          cat .nx/workspace-data/d/daemon.log
